### ISSUE TITLE
Cannont instatiate class from XML

### ISSUE THREAD

**Issue by MenilV** [ayltai/Android-Lib-VerticalMarqueeTextView#5]
I've been trying to put VerticalMarqueeTextView to my layout and inflate but I keep getting:
java.lang.ClassNotFoundException: Didn't find class "android.lib.verticalmarqueetextview.VerticalMarqueeTextView" 

Also there is no custom namespace "example". I've tried with the default app for instance: "app:marqueeSpeed" but stil nothing.

my build gradle includes: compile 'android.lib.verticalmarqueetextview:VerticalMarqueeTextView:1.0.1'

**Comment by ayltai** [comment]
Sorry the instruction in ReadMe file incorrect. The class package should be `android.lib.widget.verticalmarqueetextview.VerticalMarqueeTextView`, as illustrated in the example activity. I have corrected ReadMe now.

For the `example` namespace, did you declare `xmlns:example="http://schemas.android.com/apk/res-auto"`?

**Comment by MenilV** [comment]
I've changed the class package but I still get "unexpected name prefix example" error in xml but it works.

**Comment by ayltai** [comment]
This is a problem of Lint error reporting in Android Studio. To remove this false error, add:
`xmlns:tools="http://schemas.android.com/tools"`
`tools:ignore="MissingPrefix"`
